name: xesmf-env
channels:
  - conda-forge
dependencies:
  - black=24.8.0
  - dask=2025.1.0
  - cartopy=0.23.0
  - cftime=1.6.4
  - esmf=8.6.1
  - h5netcdf=1.3.0
  - matplotlib=3.9.2
  - netcdf4=1.7.1
  - pandas=2.2.2
  - pip=24.2
  - python=3.12.5
  - xarray=2024.7.0
  - xesmf=0.8.7